### ISSUE TITLE
Using someone else's API key isn't okay

### ISSUE THREAD

**Issue by mpetroff** [salberty/printmap01#1]
It's not okay to use someone else's API key / access token. In addition to being a terms-of-service violation for both Mapbox and MapTiler, it's also very rude.

The readme for [mpetroff/print-maps](https://github.com/mpetroff/print-maps) clearly states that you need to use your own token. Copying my token from [printmaps.mpetroff.net](https://printmaps.mpetroff.net/) is not an acceptable alternative.

By copying and using my Mapbox access token, you managed to blow through my entire API usage allotment for this billing period, with >200k requests, and using my MapTiler key, you used up almost 20% of my API request allotment for their service.

You wasted a bunch of my time, since I needed to go through the trouble of making new API keys with domain restrictions, updating the keys everywhere I'm using them, and revoking the original keys.

**Comment by salberty** [comment]
Hi Matthew, thanks for bringing this to my attention and I want to apologize for the trouble I caused.  This has been an on-and-off project of mine for the last few years.  You may recall back in 2019, you assisted me to duplicate your print-map source code so I could use the function with custom json files.  I revisited the project recently and struggled to get my version to work properly.  I ultimately found out the issue was that the source of openmaptiles changed from free.tilehosting.com to api.maptiler.com...but while trying to troubleshoot the issue, I tried your keys and neglected to change it back.  That is completely my fault and I have since resolved it.  It will never be an issue again.

**Comment by mpetroff** [comment]
Thanks for the apology. I probably should have switch to domain-restricted API keys a long time ago, so this was just motivation to finally do that.
